-- Phase 8 foundation: business identity is linked 1:1 to the existing tenant.
-- Tenant remains the technical/security isolation boundary; Business carries
-- organizational/commercial identity.

CREATE TABLE BUSINESSES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_id UUID NOT NULL,
    tenant_id UUID,
    name VARCHAR(255) NOT NULL,
    alias_name VARCHAR(255),
    address VARCHAR(500),
    city VARCHAR(120),
    state_province VARCHAR(120),
    country_code VARCHAR(3),
    zip_code VARCHAR(30),
    phone VARCHAR(50),
    contact_email VARCHAR(320),
    website_url VARCHAR(500),
    doing_business_as VARCHAR(255),
    company_registration_number VARCHAR(120),
    tax_identifier VARCHAR(120),
    duns_number VARCHAR(30),
    industry VARCHAR(160),
    employee_count_band VARCHAR(80),
    timezone VARCHAR(80),
    currency_code VARCHAR(3),
    business_status VARCHAR(40) NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    parent_business_id BIGINT,
    source VARCHAR(80),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_businesses PRIMARY KEY (id),
    CONSTRAINT uk_business_business_id UNIQUE (business_id),
    CONSTRAINT uk_business_tenant UNIQUE (tenant_id),
    CONSTRAINT fk_business_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES TENANTS (id),
    CONSTRAINT fk_business_parent
        FOREIGN KEY (parent_business_id)
        REFERENCES BUSINESSES (id)
);

CREATE INDEX idx_business_name ON BUSINESSES (name);
CREATE INDEX idx_business_tenant_id ON BUSINESSES (tenant_id);
CREATE INDEX idx_business_parent_id ON BUSINESSES (parent_business_id);
CREATE INDEX idx_business_status ON BUSINESSES (business_status);
