-- AegisAI initial database schema
-- Flyway migration: V1__initial_schema.sql
--
-- Generated from the current JPA entity model.
-- UUID primary keys are generated by the application/Hibernate.
-- PostgreSQL enum values are stored as VARCHAR because the entities use
-- @Enumerated(EnumType.STRING).
-- No inferred foreign keys are added for UUID tenantId fields where the
-- JPA model does not declare a relationship. API_KEYS.tenant_id does have
-- an explicit @ManyToOne relationship and therefore has an FK.

CREATE TABLE TENANTS (
    id UUID NOT NULL,
    tenant_code VARCHAR(255) NOT NULL,
    tenant_name VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    type VARCHAR(255),
    plan VARCHAR(255) NOT NULL,
    default_provider VARCHAR(255),
    default_model VARCHAR(255),
    created_at TIMESTAMP(6),
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uk_tenants_tenant_code UNIQUE (tenant_code)
);

CREATE TABLE tenant_entitlements (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    requests_per_minute BIGINT NOT NULL,
    requests_per_day BIGINT NOT NULL,
    monthly_token_quota BIGINT NOT NULL,
    monthly_budget NUMERIC(19,8) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT pk_tenant_entitlements PRIMARY KEY (id),
    CONSTRAINT uk_tenant_entitlement_tenant UNIQUE (tenant_id)
);

CREATE TABLE tenant_entitlement_features (
    entitlement_id UUID NOT NULL,
    feature VARCHAR(100) NOT NULL,
    CONSTRAINT uk_entitlement_feature UNIQUE (entitlement_id, feature),
    CONSTRAINT fk_entitlement_features_entitlement
        FOREIGN KEY (entitlement_id)
        REFERENCES tenant_entitlements (id)
        ON DELETE CASCADE
);

CREATE TABLE TENANT_QUOTA_USAGE (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    period_type VARCHAR(255) NOT NULL,
    period_start DATE NOT NULL,
    request_count BIGINT NOT NULL DEFAULT 0,
    token_count BIGINT NOT NULL DEFAULT 0,
    version BIGINT,
    CONSTRAINT pk_tenant_quota_usage PRIMARY KEY (id),
    CONSTRAINT UK_TENANT_QUOTA_PERIOD
        UNIQUE (tenant_id, period_type, period_start)
);

CREATE TABLE TENANT_BUDGET_USAGE (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    period_start DATE NOT NULL,
    amount_used NUMERIC(19,8) NOT NULL,
    version BIGINT,
    CONSTRAINT pk_tenant_budget_usage PRIMARY KEY (id),
    CONSTRAINT uk_tenant_budget_period
        UNIQUE (tenant_id, period_start)
);

CREATE TABLE REQUEST_COST (
    id UUID NOT NULL,
    request_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    provider VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    input_cost NUMERIC(19,8),
    output_cost NUMERIC(19,8),
    total_cost NUMERIC(19,8),
    reasoning_tokens INTEGER,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_request_cost PRIMARY KEY (id)
);

CREATE TABLE TOKEN_USAGE (
    id UUID NOT NULL,
    request_id UUID,
    provider VARCHAR(255),
    model VARCHAR(255),
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    reasoning_tokens INTEGER,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_token_usage PRIMARY KEY (id)
);

CREATE TABLE API_KEYS (
    id UUID NOT NULL,
    api_key VARCHAR(255) NOT NULL,
    client_name VARCHAR(255) NOT NULL,
    tenant_id UUID NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    expires_at TIMESTAMP(6),
    last_used_at TIMESTAMP(6),
    CONSTRAINT pk_api_keys PRIMARY KEY (id),
    CONSTRAINT uk_api_keys_api_key UNIQUE (api_key),
    CONSTRAINT fk_api_keys_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES TENANTS (id)
);

CREATE TABLE REQUEST_AUDIT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_uuid UUID NOT NULL,
    masked_prompt OID NOT NULL,
    masked_response OID,
    latency_ms BIGINT,
    model_name VARCHAR(255),
    provider VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    CONSTRAINT pk_request_audit PRIMARY KEY (id),
    CONSTRAINT uk_request_audit_request_uuid UNIQUE (request_uuid)
);

CREATE TABLE TOKEN_VAULT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_uuid UUID NOT NULL,
    token VARCHAR(100),
    encrypted_value OID NOT NULL,
    pii_type VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_token_vault PRIMARY KEY (id)
);

-- Explicitly indexed lookup paths used by the application.
CREATE INDEX idx_tenant_entitlements_tenant_id
    ON tenant_entitlements (tenant_id);

CREATE INDEX idx_tenant_quota_usage_tenant_id
    ON TENANT_QUOTA_USAGE (tenant_id);

CREATE INDEX idx_tenant_budget_usage_tenant_id
    ON TENANT_BUDGET_USAGE (tenant_id);

CREATE INDEX idx_request_cost_tenant_id
    ON REQUEST_COST (tenant_id);

CREATE INDEX idx_request_cost_request_id
    ON REQUEST_COST (request_id);

CREATE INDEX idx_token_usage_request_id
    ON TOKEN_USAGE (request_id);

CREATE INDEX idx_api_keys_tenant_id
    ON API_KEYS (tenant_id);

CREATE INDEX idx_request_audit_request_uuid
    ON REQUEST_AUDIT (request_uuid);

CREATE INDEX idx_token_vault_request_uuid
    ON TOKEN_VAULT (request_uuid);
