ALTER TABLE PERSONAL_CHAT_SESSIONS ADD COLUMN parent_session_id UUID;
ALTER TABLE PERSONAL_CHAT_SESSIONS ADD COLUMN branch_message_id UUID;
CREATE INDEX idx_chat_session_parent ON PERSONAL_CHAT_SESSIONS(parent_session_id);
