ALTER TABLE PERSONAL_PROVIDER_CONNECTIONS
    ADD COLUMN api_key_last4 VARCHAR(4);

UPDATE PERSONAL_PROVIDER_CONNECTIONS
SET api_key_last4 = '****'
WHERE api_key_last4 IS NULL;

ALTER TABLE PERSONAL_PROVIDER_CONNECTIONS
    ALTER COLUMN api_key_last4 SET NOT NULL;