-- AegisAI tenant operational schema
-- Executed once for every tenant_<uuid> schema.

CREATE TABLE REQUEST_AUDIT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_uuid UUID NOT NULL,
    masked_prompt OID NOT NULL,
    masked_response OID,
    latency_ms BIGINT,
    model_name VARCHAR(255),
    provider VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    CONSTRAINT pk_request_audit PRIMARY KEY (id),
    CONSTRAINT uk_request_audit_request_uuid UNIQUE (request_uuid)
);

CREATE TABLE TOKEN_USAGE (
    id UUID NOT NULL,
    request_id UUID,
    provider VARCHAR(255),
    model VARCHAR(255),
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    reasoning_tokens INTEGER,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_token_usage PRIMARY KEY (id)
);

CREATE TABLE TOKEN_VAULT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_uuid UUID NOT NULL,
    token VARCHAR(100),
    encrypted_value OID NOT NULL,
    pii_type VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_token_vault PRIMARY KEY (id)
);

CREATE TABLE REQUEST_COST (
    id UUID NOT NULL,
    request_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    provider VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    input_cost NUMERIC(19,8),
    output_cost NUMERIC(19,8),
    total_cost NUMERIC(19,8),
    reasoning_tokens INTEGER,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_request_cost PRIMARY KEY (id)
);

CREATE TABLE TENANT_QUOTA_USAGE (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    period_type VARCHAR(255) NOT NULL,
    period_start DATE NOT NULL,
    request_count BIGINT NOT NULL DEFAULT 0,
    token_count BIGINT NOT NULL DEFAULT 0,
    version BIGINT,
    CONSTRAINT pk_tenant_quota_usage PRIMARY KEY (id),
    CONSTRAINT UK_TENANT_QUOTA_PERIOD
        UNIQUE (tenant_id, period_type, period_start)
);

CREATE TABLE TENANT_BUDGET_USAGE (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    period_start DATE NOT NULL,
    amount_used NUMERIC(19,8) NOT NULL,
    version BIGINT,
    CONSTRAINT pk_tenant_budget_usage PRIMARY KEY (id),
    CONSTRAINT uk_tenant_budget_period
        UNIQUE (tenant_id, period_start)
);

CREATE TABLE ROUTING_OUTCOME (
    id UUID NOT NULL,
    request_id UUID NOT NULL,
    tenant_id UUID,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(255) NOT NULL,
    routing_strategy VARCHAR(64),
    selected_score DOUBLE PRECISION,
    selected_rank INTEGER,
    candidate_count INTEGER,
    selection_reason VARCHAR(128),
    routing_priority VARCHAR(64),
    extensive_research BOOLEAN NOT NULL DEFAULT FALSE,
    execution_role VARCHAR(255),
    success BOOLEAN NOT NULL,
    failure_category VARCHAR(128),
    latency_ms BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_routing_outcome PRIMARY KEY (id),
    CONSTRAINT uk_routing_outcome_request UNIQUE (request_id)
);

CREATE INDEX idx_request_audit_request_uuid
    ON REQUEST_AUDIT (request_uuid);

CREATE INDEX idx_token_usage_request_id
    ON TOKEN_USAGE (request_id);

CREATE INDEX idx_token_vault_request_uuid
    ON TOKEN_VAULT (request_uuid);

CREATE INDEX idx_request_cost_tenant_id
    ON REQUEST_COST (tenant_id);

CREATE INDEX idx_request_cost_request_id
    ON REQUEST_COST (request_id);

CREATE INDEX idx_tenant_quota_usage_tenant_id
    ON TENANT_QUOTA_USAGE (tenant_id);

CREATE INDEX idx_tenant_budget_usage_tenant_id
    ON TENANT_BUDGET_USAGE (tenant_id);

CREATE INDEX idx_routing_outcome_provider_model
    ON ROUTING_OUTCOME (provider, model);

CREATE INDEX idx_routing_outcome_created_at
    ON ROUTING_OUTCOME (created_at);

CREATE INDEX idx_routing_outcome_tenant
    ON ROUTING_OUTCOME (tenant_id);